on: [push]

jobs:
  yaml_gen:
    runs-on: ubuntu-latest
    name: A job to generate yaml region tags for tracking
    steps:
    - name: yaml gen action step
      id: yamlgen
      uses: askmeegs/yaml-region-tag-generator@v0.0.2
      env:
        ID_RSA: ${{ secrets.id_rsa }}
        KNOWN_HOSTS: ${{ secrets.known_hosts }}
        PRODUCT: "istio"
